### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by lgg** [notrurs/Serious_PySam#1]
How i can install and use this game?

**Comment by notrurs** [comment]
@lgg, at the moment game in alpha state, but if you want to play, you can download the repo and start game through command `python serious_pysam.py`. Note, that you need python at least 3.6 version. And don't forget about `requirements.txt`
I'll release the 1.0 version as soon as possible and then write about game in README, keep enthusiasm :)

**Comment by notrurs** [comment]
@lgg README added :)
